import { deleteHabit, getHabitsFromLocalStorage } from "../functions";
import { HiddenForm } from "./hiddenForm";

function CreateAHabit({
  habit,
  forEditing,
  setForEditing,
  setEditId,
  setIsItOpened,
}) {
  //  all html code is generated by claude. Not gonna waste time writing html code in a react training project.

  const note = habit["note"];
  const name = habit["name"];
  const id = habit["id"];

  return (
    <>
      <div
        className="relative bg-neutral-800 border border-neutral-700 rounded-xl p-4 max-w-60 w-full"
        data-id={id}
      >
        <span className="text-xl">💧</span>

        <div className="absolute top-4 right-4 flex gap-3 text-neutral-400 ">
          {note !== "" && (
            <button
              aria-label="View note"
              className="cursor-pointer"
              title={note}
            >
              📝
            </button>
          )}
          <button
            aria-label="Edit habit"
            onClick={(event) => {
              const id = event.target.parentElement.parentElement.dataset.id;


              setIsItOpened(true);
              setForEditing(true);
              setEditId(id);
            }}
            className="cursor-pointer"
          >
            ✏️
          </button>
          <button
            aria-label="Delete habit"
            className="cursor-pointer"
            onClick={deleteHabit}
          >
            🗑️
          </button>
        </div>

        <div className="text-sm font-medium text-neutral-100 mt-2">{name}</div>
        <p className="text-xs text-neutral-400 mt-1 mb-3">12 day streak</p>

        <button className="w-full text-sm border border-neutral-600 rounded-lg py-1.5 text-neutral-300 cursor-pointer">
          Mark done
        </button>
      </div>
    </>
  );
}
export { CreateAHabit };
